apiVersion: apps/v1
kind: Deployment
metadata:
  name: magma-api
  namespace: magma-api
spec:
  selector:
    matchLabels:
      app: magma-api
  template:
    metadata:
      labels:
        app: magma-api
    spec:
      containers:
      - name: magma-api
        image: hexeption/magma-api:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: magma-api
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
